### ISSUE TITLE
Not loading Session of CWD

### ISSUE THREAD

**Issue by Leo310** [glepnir/dbsession.nvim#4]
**Problem:**
When I have multiple saved Sessions from different directories and want to load one from the CWD it only opens the default session:
![Screenshot_20230325_121014](https://user-images.githubusercontent.com/48623649/227714164-8cc8bc85-38a4-486f-8d7c-f5158fc89490.png)

**Wish:**
Would be great if it automatically loads the session of the current directory and not the default one when executing :SessionLoad

**Comment by Leo310** [comment]
Not sure, but still not working on my end.
Same behavior as before.

**Comment by glepnir** [comment]
hmm in my local it works ..
