### ISSUE TITLE
Why timestamping? It creates so many sessions

### ISSUE THREAD

**Issue by Leo310** [glepnir/dbsession.nvim#6]
These are all different sessions for one project:
![image](https://user-images.githubusercontent.com/48623649/228002319-daee98d7-dae7-474c-a5f4-068106a656bf.png)

I would just want to load the latest one.

**Comment by glepnir** [comment]
wried. it should load the latest one.  because when you have mulitple sessions in this project .you can choice one to load...

**Comment by Leo310** [comment]
Probably it loads the latest one. But it saves a new one every time I quit neovim. And this happens quite often. I think nobody would want to choose between all those sessions by looking at the timestamp. So I propose to just save one session per project. And if one might want to choose between multiple sessions of one project he can name them.

**Comment by glepnir** [comment]
so the suggest is set the default session name just project name right ?

**Comment by Leo310** [comment]
yes basically.

**Right now:**
One Project -> multiple timestamped session files

**Wish:**
One Project -> one session file

This reduces bloat and makes choosing a session easier.

**Comment by glepnir** [comment]
that's more easy . so if someone want mulitple sessions he must give a session name then .

**Comment by Leo310** [comment]
yeah imo this is a better solution.
Nobody would choose between sessions based on a hardly readable timestamp.

**Comment by Leo310** [comment]
To make it clear:
I still want different session files for different projects that are automatically created when calling :SaveSession.
I just don't want different session files for one and the same project.

**Comment by glepnir** [comment]
just use string of `getcwd` then convert the path to `_` then concat .

**Comment by glepnir** [comment]
after i finish bug fix in lspsaga .  i will rewrite session name .
