### ISSUE TITLE
How to enter/close session?

### ISSUE THREAD

**Issue by joelpeapen** [glepnir/dbsession.nvim#8]
I'm migrating from [startify](https://github.com/mhinz/vim-startify) and so far it's good, but is there a way to enter a session/workspace directly without bringing up telescope, like startify does, and is there a command to close a session, like SClose? Thanks.

**Comment by glepnir** [comment]
just use command ? `SessionLoad name` ?

**Comment by j-ole** [comment]
yes i only saw that now. the `Session` commands don't show up, only `DbProjectDelete` is there. `Dashboard` doesn't bring up the dash either.

**Comment by glepnir** [comment]
this is another plugin so not relate dashboard. prefix is `SessionXXX`

**Comment by j-ole** [comment]
there are no session commands.

**Comment by glepnir** [comment]
what you mean no `SeesionLoad` `SessionSave` ? how you load dbsession ?

**Comment by j-ole** [comment]
ah, yes, the setup was wrong. thanks!

also, is there a way to quit a session without closing all the buffers? Can i use dbsession with dashboard? Right now it doesn't detect the file sessions in `stdpath("cache")/nvim/session` and display it under projects. i have `nvim.vim` session but only file paths show up.

<details>
<summary> Dash </summary>
![dash.jpg](https://github.com/nvimdev/dbsession.nvim/assets/67512946/20cc8c14-0c2b-4d2f-8864-1df3fea1e661)
</details>

**Comment by glepnir** [comment]
> Can i use dbsession with dashboard?

yes .

> Right now it doesn't detect the file sessions in stdpath("cache")/nvim/session and display it under projects.

it will read the session dir and you can use tab to see it . I create `test` file by `touch` command unser `.cache/nvim/session` folder  and I can see it in complete list


![image](https://github.com/nvimdev/dbsession.nvim/assets/41671631/d4795ac6-46c4-42b4-83ae-1869425c40f6)

**Comment by j-ole** [comment]
will sessions show up under projects in dashboard like it does in startify?

![startify](https://github.com/nvimdev/dbsession.nvim/assets/67512946/891146a8-cf34-424f-bc07-5c2146f7ffe9)

**Comment by glepnir** [comment]
oh you mean show in dashboard buffer. in new version dashboard support fully custom and provide standard interface to write own theme . also you can do it in new version hyper . maybe after one week will release .
